[whitelist]
# As of v4, gitleaks only matches against filename, not path in the
# files directive.  Leaving content for backwards compatibility.
files = [
  "plugins/modules/*.py",
  "tests/unit/test_*.py",
  "tests/unit/v1/*.yaml",
]
